Repository dolosse/dolosse, pull requests merged in 2019-11, with the labels that each got.

#81 Update Pixie-16 Data Decoder
  dolosse/common/__init__.py
  dolosse/common/tests/__init__.py
  dolosse/common/tests/decode_buffer_tests.py
  dolosse/constants/data.py
  dolosse/hardware/xia/pixie16/list_mode_data_decoder.py
  dolosse/hardware/xia/pixie16/tests/list_mode_data_decoder_tests.py
  dolosse/hardware/xia/pixie16/tests/test_data.py
  setup.py
Labels: acquisition, analysis

#82 Adds codecov to project
  .travis.yml
  README.md
Labels: admin, documentation, enhancement, housekeeping

#85 Add new description to feature.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: bug, documentation, housekeeping

#87 Feature/84 lmdm codecov
  dolosse/hardware/xia/pixie16/list_mode_data_mask.py
  dolosse/hardware/xia/pixie16/tests/list_mode_data_mask_tests.py
  dolosse/hardware/xia/pixie16/tests/list_mode_data_mask_unit_tests.py
Labels: enhancement, housekeeping

#88 Feature/86 lmdd codecov
  dolosse/hardware/xia/pixie16/list_mode_data_decoder.py
  dolosse/hardware/xia/pixie16/tests/list_mode_data_decoder_tests.py
  dolosse/hardware/xia/pixie16/tests/test_data.py
Labels: housekeeping
